{% set name = "jupyter_pivottablejs" %}
{% set version = "0.9.0" %}
{% set sha256 = "9f0f9f692330f2f635dc37f05ad99da84646e4f3dbf9fe849cf6889de4b3210b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/fb/78/517225db7bc2b449dc75d491cdf3bb0036ca63c064eb38f95ba38fcb9f9e/pivottablejs-0.8.0.tar.gz#md5=6e828cfc72ef0502325d726a052c1f5f
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ipython

test:
  imports:
    - pivottablejs

about:
  home: https://github.com/nicolaskruchten/jupyter_pivottablejs
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Drag and drop Pivot Tables and Charts for Jupyter/IPython Notebook, care of PivotTable.js'
  description: |
    Drag and drop Pivot Tables and Charts for Jupyter/IPython Notebook
  doc_url: http://nicolas.kruchten.com/content/2015/09/jupyter_pivottablejs/
  dev_url: https://github.com/nicolaskruchten/jupyter_pivottablejs

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
