travis:
  secure:
    BINSTAR_TOKEN: r3kJ9bj0REB9V5uriJAhjDwMo9kjHgx3LnXwguHMVelzYRc/SZhlDpPpAZD+SAid0zPHROkuhrLr+0DO/xXJJ1SIwZTapQ0nJsSLQpN3PmvWS6QQ+7Y6oXwRZVWoT3xAYhrvayzPGUurr9lLbZgQAlCpF1jh9lUhvo8QjU/apYZhtA4goO4BDk6IfjB29ljhi7Kq6phA2m+pWfYjyKA2B2hbl9sFDMxt2Z7XmxDwr4Lm4z6nHkAwrmgq6+ArPg+g41Aad72E3iaDPFUBRGeUE/TPeWmfgpeWomxxXSTjVGTwYMG7PeeXyiYA/X7ProqoRFG63Ux2t155Be1UytREjjwrlAAtVBXJKprFS3LHIZwqa9Ufs2g6693mccI8qtagXBSsGo284IQLat+cUZitd1+S22AESgFPgL3xGLV+7dWuZKeXbQnDR3yXEzw9LotlcfNDRrrdAiXyZJ6ihPBWTRxhD2YGG2WeLHOITJVmepFKQOLfJTV23/aps3sZXcr/U9dj99tuGqW/4QYyIXwCN+aMiysxMPgi9+GQRIuCbUZfwVyeQOcJNKEf2vHeU/iCTk0wFIxRYrIj2neBdrJfYLgAn6yah+IcVqBAUQH8q0YYFBXw+w/phHbL79Gipmm4Oab0jliPR1judZo6MWWjB7pwheng8R2dvieBlKewRjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
