travis:
  secure:
    BINSTAR_TOKEN: 5BuAYKm0/4g7oUIR9S0O2wR0TjGP68BYn8FxKTWtN0MbadhifEdHhHOKr7eRu8mMQ3w62xeUjy+kZai+lnRMhJcKeTP/8AVd12hwwYALN4vXxVyvFVlT/Qh+36XvC9n9FoOJvh4bk3rrTO9XWAs99qjp0Q3b9MPCaPokHjuseRZ7jq12d3dZUqRmq0T0ycqoV/KRyeSJvW4sRmGFfYTm31rLLS8Jt3yZQkU/Ax1Amai3ejGIDtmpCZUI7rvN0J4KgiG8WSVZ6V8ILw10w70zSeBT/wYregBR+IIOiGqO8JheyrHrY7Xd26uSxYKgPow1yXKVctg6oeFM2zVsGSENfrro1PlUUWU4PruDBBuIAMxAZvdv8nS37qiLfHwA4HVUrS8JI4v8l6jtKJ5w9E7JHEE8rwRWg6UlI5BrO+iWGiNatW17FPorOkG9gfSJfPFq9iGeSwexAU+ORp5HfBwjX6lPY3GRNAB1v07cA630ctgBdpy6cHjXv6fNFL0qW8OVp+EN2Cce5EXe1Nu2atnHvnrfNDv0ljEOiWQr4qez+bod+dM2TlaNnFN4W8C7iMRMH1yiQWmPnpE6kWXPcdV16u3iQMR2XxklJWiDQGRI3nxwRvAsDDxwvisOavd4FztJdLm5N/1yNopCOCUVP8Gtj1IdFAVH5l5bvjG/wgyZRJw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
