travis:
  secure:
    BINSTAR_TOKEN: nK/2pD7jhLQUwgo0Wk7mnQYfPW+idqrV2bmCQsC6BRTjKNzoQCHfjE/sB+RREvjmSMKFIoHXm1SZKWbB2z+mHj3iUAoDPiaItiNn0J+oO0DShFXw5p1/5RlOdAB3SlyGncCd7JTy3zNeuwefCfxS/h8lrQk3WoJIUZKLXHHhLKEnWmaH4YjAWuJ6SmEEJ74MvyGKO8YW5NRVQ8hXU0+wL2eMU6NdqCrYJhR0ZyiuiV2pbC1x9cnyA4ENBeIjdgjKR4M5y+4RmbJRc1RabYSHwV5MOJw/+l9XJ43JZtelnbXDqV5rpQtkJaBnj+ZZJrSjKBkD6MNqwXrWzlMmwWtHX2rfMBFNbInRUIRfZ7KEJj5iF/2eCKMJf2OB64OnrC1CtJJQlNE0M9okH1bwW4196mc1vyypUpDiPsspl53R2Rt4rRojnSOJR+Xm6iuQz2AXLsILPyHIPIRWyu13m6aPL+kSRJtarr+qWvMrF5Ot590cX/2buyiVq9kBOucI7UqhmZAATCfjleQewpiNZKmC5XD5iEYTwDfU/OhHWrQ88hKcx5isN+MdzuEul8LsonpLTS7/A9eqUIQkOu9m4+MCbAZHDHHBIVkRBC0HoBgodJTSE7tbhyqlHlX6X/g/OjCMC0aWSCFKD1xRCAzdKajvJCjo1MT3cFNHzj559b21qNo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
